services:
  - type: web
    name: sportsight-backend
    env: node
    region: oregon
    plan: free
    branch: main
    buildCommand: npm install && npm run build
    startCommand: node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: PAYPAL_CLIENT_ID
        sync: false
      - key: PAYPAL_CLIENT_SECRET
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: PORT
        value: 10000
      - key: FRONTEND_URL
        value: https://www.sportsight.app
